exclude: ^tests/resources/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      # - id: check-added-large-files
      # - id: check-ast
      # - id: check-builtin-literals
      # - id: check-case-conflict
      # - id: check-docstring-first
      # - id: check-merge-conflict
      # - id: check-toml
      # - id: debug-statements
      # - id: end-of-file-fixer
      # - id: forbid-new-submodules
      # - id: mixed-line-ending
      # - id: trailing-whitespace
      #   exclude_types: [ svg ]

  # - repo: https://github.com/astral-sh/ruff-pre-commit
  #   rev: v0.6.9
  #   hooks:
  #     - id: ruff
  #       args: [--fix, --exit-non-zero-on-fix, --show-fixes]
  #     - id: ruff-format


  # - repo: https://github.com/pre-commit/pygrep-hooks
  #   rev: v1.10.0
  #   hooks:
  #     - id: python-check-mock-methods
  #     - id: python-no-eval
  #     - id: python-no-log-warn
  #     - id: python-use-type-annotations

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args:
          - --fix
          - --exit-non-zero-on-fix
          - --show-fixes
          - --ignore=B018
          - --ignore=F821
          - --exclude=notebooks/
      - id: ruff-format
